global:
  # qq服务器
  smtp_smarthost: 'smtp.qq.com:25'
  # 发邮件的邮箱　
  smtp_from: '605336558@qq.com'
  # 发邮件的邮箱用户名，也就是你的邮箱　　　　　　　
  smtp_auth_username: '605336558@qq.com'
  # 发邮件的邮箱密码
  smtp_auth_password: 'ckgubwuoxicwbcdb'
  # 不进行tls验证　　　　　　　
  smtp_require_tls: false　　　　　　　　

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
  - name: 'live-monitoring'
  email_configs:
    - to: '605336558@qq.com'　　　　　　　　#收邮件的邮箱