version: '3.6'
services:
  mongo-container:
    image: mongo:3.4.20
    container_name: mongodb
    # 目前，仅支持MONGO_INITDB_ROOT_USERNAME和MONGO_INITDB_ROOT_PASSWORD
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - mongodb:/home/mongodb
      - datadb:/data/db
      - entrypoint:/docker-entrypoint-initdb.d/
    command: mongod

volumes:
  mongodb:
  datadb:
  entrypoint: